global using OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities;
global using OmniSharp.Extensions.LanguageServer.Protocol.Document;
global using OmniSharp.Extensions.LanguageServer.Protocol.Models;
global using OmniSharp.Extensions.LanguageServer.Protocol.Server;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using OmniSharp.Extensions.LanguageServer.Server;
global using Serilog;
global using OmniSharp.Extensions.LanguageServer.Protocol;
global using MediatR;
global using System.Linq;
global using OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities;
using System.Runtime.CompilerServices;